---
abstract: 'Alternative syntax for describing Catalyst routes'
author:
  - 'John Napiorkowski <jjnapiork@cpan.org>'
build_requires:
  Catalyst: '5.90093'
  Catalyst::Test: '0'
  HTTP::Request::Common: '0'
  Moose: '2.1403'
  MooseX::MethodAttributes: '0'
  Test::Most: '0.34'
  Types::Standard: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.041, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catalyst-ControllerRole-At
requires:
  Catalyst::ActionRole::NamedFields: '0.01'
  Catalyst::ActionRole::QueryParameter: '0.07'
  Moose: '2.1403'
resources:
  bugtracker: https://github.com/jjn1056/Catalyst-ControllerRole-At/issues
  homepage: https://github.com/jjn1056/Catalyst-ControllerRole-At
  repository: https://github.com/jjn1056/Catalyst-ControllerRole-At.git
version: '0.001'
